### ISSUE TITLE
퀴즈 페이지 레이아웃 및 기능 구현

### ISSUE THREAD

**Issue by kyhyun** [InQD/inqd-client#13]
## Issue
- type : feat

## Description
- 퀴즈 페이지 레이아웃 및 기능 구현

## TODO
- [ ] 퀴즈 페이지 레이아웃 및 기능
  - [x] 헤더 공용 - 끝내기 버튼 ( 완료 페이지 이동 )
  - [ ] 메인 - 질문을 보여주는 카드
  - [ ] 메인 - 타이머 레이아웃 및 애니메이션
  - [ ] 푸터 - 다음 질문 넘어가기

## ECT
- 타이머 있는 디자인 시안
<img width="297" alt="image" src="https://user-images.githubusercontent.com/77887712/187170684-35a45fcd-4472-406a-a7a4-775f358b4e5c.png">
- 타이머 없는 디자인 시안
<img width="296" alt="image" src="https://user-images.githubusercontent.com/77887712/187170855-fb4ee141-0d97-4da3-ab87-2c3990de0b2a.png">
