### ISSUE TITLE
29일 회의 후 수정 작업 - 코드 리팩토링 및 추가 작업

### ISSUE THREAD

**Issue by kyhyun** [InQD/inqd-client#16]
## Issue
- type : refactor

## Description
- 메인 페이지 / 질문 생성 페이지 기능 변경 및 리팩토링

## TODO
- [x] 메인 페이지
  - [x]  시작 버튼 애니메이션 처리 ( mock 데이터 반영 )  
- [x] 질문 생성 페이지
  - [x] 필수 질문 버튼 색상 변경 ( 카테고리의 색상 반영 ) 
  - [x] 공통 헤더 컴포넌트 적용
  - [x] 디스플레이 컴포넌트 적용
