### ISSUE TITLE
fix: Merge 후 세부 수정사항

### ISSUE THREAD

**Issue by zellytozelly** [InQD/inqd-client#19]
## Issue
- type : fix

## Description
- QuizCard 관련 수정

## TODO
- [x] 구현해야할 것 
  -  ~~createQuiz에서, QuizCard 위치 배열~~
  - [x] createQuiz에서, QuizCard src 클릭 안되게 옵셔널
  - [x] 헤더에서, < 버튼 눌렀을 때 위치 조정가능하도록 변경
  - [x] QuizCard src에 `?` 연산자 props 체크
  - [x] createQuiz에서, QuizCard 글자수 넘어가면 안보이게 처리
  - [x] @keyframes fadeInDown from to 로 변경

## ECT
- 기타 논의사항
  - [제안] createQuiz에서, 인성 기술질문 active만 살리면 애니메이션 효과가 더 극대화 될 듯 합니다! 
  - [고민사항] /setting에서 영어 검색시, 대문자 검색에 대한 논의
