### ISSUE TITLE
회의 후 추가 수정 작업 - 링크 연결/타이머 값

### ISSUE THREAD

**Issue by zellytozelly** [InQD/inqd-client#2]
## Issue
- type : refactor

## Description
- 인터뷰헬퍼 설정 기능 추가

## TODO
- [ ] 설정 아이콘 링크 연결
- [ ] 타이머 00 값 안들어가는 문제 해결
- [ ] 라우터 format setting
