### ISSUE TITLE
fix : issue-16 Merge 후 추가 수정

### ISSUE THREAD

**Issue by kyhyun** [InQD/inqd-client#20]
## Issue
- type : fix

## Description
- #16 작업 이후 main 및 createQuiz 추가 수정

## TODO
- 해결해야할 것
  - main
    - [x] 데이터 채워져있을 때, fade-out 애니메이션 제거
    - [x] 데이터에 따라 fill-color 애니메이션 정상 동작 수행
  - createQuiz
    - [x] 불필요한 hover 효과 제거

## ECT
- 기타 논의사항
  - 간혹 공통 헤더 부분의 뒤로 가기를 수행하는 버튼에서 내비게이션을 여러 번 눌러도 이동이 안되는 버그가 있어서 기능이 정상 동작하는지 크로스 체크해봐야할 것 같습니다.

**Comment by zellytozelly** [comment]
Mock 데이터 -> 로컬스토리지에 오늘 나올 질문들 id 값만 저장
