### ISSUE TITLE
메인 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by kyhyun** [InQD/inqd-client#3]
## Issue
- type : feat

## Description
- 인터뷰헬퍼 메인(홈 / 랜딩) 페이지 레이아웃 구현

## TODO
- 구현해야할 것 
  - [x] 설정 버튼
  - [x] 플로팅 메세지 (fade-in/ fade-out)
  - [x] 초기 화면 로고
  - [x] 면접 시작 버튼
    - [x] fill-color 애니메이션

### 디자인 스크린샷
- 초기 상태 화면
![image](https://user-images.githubusercontent.com/77887712/186118627-2e55cbe8-a59a-4dc9-bd22-1c78644f0c77.png)

- 플로팅 메시지
![image](https://user-images.githubusercontent.com/77887712/186117953-fc017523-218a-498f-9566-2bfad6c8740e.png)
- fill-color 애니메이션
![image](https://user-images.githubusercontent.com/77887712/186118288-ebff5bd6-6b04-45bd-807f-4bce6a027bc4.png)
